version: '3.2'
services:
  companyservice:
   image: companyservice
   build: CompanyService/
   restart: always
   ports:
     - 8082:8082
   expose:
     - 8082
  stockservice:
   image: stockservice
   build: StockService/
   restart: always
   ports:
     - 8084:8084
   expose:
     - 8084