server:
  port: 0
  servlet:
    context-path: /api/v1.0/market/company
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
spring:
  application:
    name: CompanyService
  datasource:
    url: jdbc:mysql://localhost:3306/marketdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
springdoc:
  swagger-ui:
    enabled: true
  pathsToMatch: /*, /**
